// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpfD9J0rur-nnOLPyWhE5pMmGW9OCrUF4',
    appId: '1:538774974968:web:40b1f8fda02d278b1de60d',
    messagingSenderId: '538774974968',
    projectId: 'frifri-380f1',
    authDomain: 'frifri-380f1.firebaseapp.com',
    storageBucket: 'frifri-380f1.appspot.com',
    measurementId: 'G-QPJFP3BWEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4mocXhwwTr-DZteh6bXO6528e36ErVts',
    appId: '1:538774974968:android:5271fd51ae3d12de1de60d',
    messagingSenderId: '538774974968',
    projectId: 'frifri-380f1',
    storageBucket: 'frifri-380f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7e-zL0-nOyMaH6QrhSJ9TiKZf9S5Ya8s',
    appId: '1:538774974968:ios:143e26d572d99c4b1de60d',
    messagingSenderId: '538774974968',
    projectId: 'frifri-380f1',
    storageBucket: 'frifri-380f1.appspot.com',
    iosBundleId: 'com.example.frifri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7e-zL0-nOyMaH6QrhSJ9TiKZf9S5Ya8s',
    appId: '1:538774974968:ios:8c777f3eff800cca1de60d',
    messagingSenderId: '538774974968',
    projectId: 'frifri-380f1',
    storageBucket: 'frifri-380f1.appspot.com',
    iosBundleId: 'com.example.frifri.RunnerTests',
  );
}
